config/routes.rb
Rails.application.routes.draw do
  
  root to: "cards#index", as: 'home_page'
  get 'pages/about', to: 'pages#about', as: 'about_page'
  get 'pages/how_to_use', to: 'pages#how_to_use', as: 'how_to_use_page'
  get 'pages/educators', to: 'pages#educators', as: 'educators_page'
  get 'pages/feedback', to: 'pages#feedback', as: 'feedback_page'
  devise_for :users
  resources :users, :except => [:index]
  get 'cards/study', to: 'cards#study', as: 'study_page'
  resources :cards
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/about.html.erb
<h1>About flash card app</h1>
<p>Information about the app</p>

app/views/pages/educators.html.erb
<% if current_user %>
    <% if current_user.has_role?(:educator) %>
    <% # page that is rendered if the user is an educator%>
    <h2>Hello, you are an educator</h2>
    <p>You have permissions to endorse cards, and edit student created cards. </p>
    <% else %>
    <%# page that is rendered if the user is not an educator%>
    <h2>Become an educator<h2>
    <p>As an educator you can:</p>
    <ul>
        <li>Endorse cards created by students</li>
        <li>Automatically endorse cards you create</li>
        <li>...more features coming soon...</li>
    </ul>
    <p>Edit your profile to become an educator</p>

    <% end %>
<% end %>

app/views/pages/home.html.erb
<% if user_signed_in? %>
    Show user's flash cards
<% else %>    
    <h1>Welcome to flash card app</h1>
    <ul>
        <li><%= link_to('Login', new_user_session_path) %></li>
        <li><%= link_to('Sign Up', new_user_registration_path) %></li>
        <li>Login as teacher</li>
    </ul>
    
<% end %>

<p> Showing all flash card questions </p>
<section class='cards-list'>
<% @cards.each do |card| %>
    <div class='card'>
        <div class='container'>
            <p><%= card.question %></p>
            <br>
            <%= link_to 'see details', card_path(card.id) %>
            <br>
        </div>
    </div>
<% end %>
</section>

app/views/pages/how_to_use.html.erb
<h1>How to Use the App</h1>
<p>Information for the user on how to use the app</p>