config/routes.rb
Rails.application.routes.draw do
  
  root to: "cards#index", as: 'home_page'
  get 'pages/about', to: 'pages#about', as: 'about_page'
  get 'pages/how_to_use', to: 'pages#how_to_use', as: 'how_to_use_page'
  get 'pages/educators', to: 'pages#educators', as: 'educators_page'
  get 'pages/feedback', to: 'pages#feedback', as: 'feedback_page'
  devise_for :users
  resources :users, :except => [:index]
  get 'cards/study', to: 'cards#study', as: 'study_page'
  resources :cards
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user

  has_one_attached :question_picture
  has_one_attached :answer_picture
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
    # if current_user.has_role?(:educator) && (@card.user_id != current_user.id)
    #   redirect_to home_page_path, notice: "You can't edit cards you didn't create!"
    # end
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)
    @card.user_id = current_user.id
    @card.question_picture.attach(params[:card][:question_picture])
    @card.answer_picture.attach(params[:card][:answer_picture])
    # @card.save

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    @card.question_picture.attach(params[:card][:question_picture])
    @card.answer_picture.attach(params[:card][:answer_picture])

    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def study
    @cards = Card.first(20)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.require(:card).permit(:question, :answer, :endorsed)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_with(model: card, local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
        <% card.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class='new-card'>

    <div class="field">
      <%= form.label :question %>
      <%= form.text_area :question %>
    </div>

    <div class="field">
      <%= form.file_field :question_picture %>
    </div>
    <hr>
    <div class="field">
      <%= form.label :answer %>
      <%= form.text_area :answer %>
    </div>

    <div class="field">
      <%= form.file_field :answer_picture %>
    </div>
    
    <%# only visible to educators, checkbox checked by default to save time %>
    <% if current_user.has_role?(:educator)%>
      <div class="field">
        <%= form.label :endorsed %>
        <%= form.check_box :endorsed, { checked: true }%>
      </div>
    <% end %>

</div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<h1>Cards</h1>
  
  <section class='cards-list'>
    <% @cards.each do |card| %>
    <div class='card'>
      <div class='container'>
        <div class='endorsement-tick'>
            <%= fa_icon "check-square" if card.endorsed%>
        </div>
        <%= card.question %>
        <% if card.question_picture.attached?%>
          <%= fa_icon "image x" %>
        <% end %>
        <hr>
        <%= card.answer %>
        <% if card.answer_picture.attached?%>
          <%= fa_icon "image x" %>
        <% end %>
        <hr>
        <%= image_tag(card.user.profile_picture, height: '32', width: '32') if card.user.profile_picture.attached? %>
        <%= link_to fa_icon("eye 2x"), card %>
        <%# only show edit and delete options to user if they created the card or if the user is an educator%>
        <% if current_user.id == card.user_id %>
          <%= link_to fa_icon("edit 2x"), edit_card_path(card) %>
          <%= link_to fa_icon("trash 2x"), card, method: :delete, data: { confirm: 'Are you sure?' } %>
        
        <% #eductors can endorse cards %>
        <% elsif current_user.has_role?(:educator) && card.endorsed != true %>
          <%= link_to fa_icon("edit 2x"), edit_card_path(card) %>
        
        <% #users who did not create the card and do not have educator permissions cannot delete or edit cards%>
        <% else %>

        <% end %>
      </div>
    </div>
    <% end %>
  </section>

<br>

<%= link_to 'New Card', new_card_path %>
<br>
<%= link_to 'Study Now', study_page_path %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p>
  <strong>Question:</strong>
  <%= @card.question %>
</p>

<%= image_tag(@card.question_picture) if @card.question_picture.attached? %>

<p>
  <strong>Answer:</strong>
  <%= @card.answer %>
</p>
 <%= image_tag(@card.answer_picture) if @card.answer_picture.attached? %>

<p>
  <strong>Endorsed:</strong>
  <%= @card.endorsed %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @card.user.name %>
</p>

<% if current_user.has_role?(:educator) || @card.user_id == current_user.id %>
<% # only show the edit button if the user is an educator or they created the card %>
  <%= link_to 'Edit', edit_card_path(@card) %> |
<% end %>
<%= link_to 'Back', cards_path %>

app/views/cards/study.html.erb
<% @cards.each do |card| %>
    <section class='cards-list'>
        <div class='card'>
            <div class='study-mode'>
                <%= card.question %>
                <br>
                <%= image_tag(card.question_picture, height: '100') if card.question_picture.attached? %>
                <br>

                <a class='reveal-answer'>Hover to reveal answer</a>
                <div class='answer'>
                    <%= card.answer %>
                    <br>
                    <%= image_tag(card.answer_picture, height: '100') if card.answer_picture.attached? %>
                </div>
            </div>
        </div>
    </section>
<% end %>