config/routes.rb
Rails.application.routes.draw do
  
  root to: "cards#index", as: 'home_page'
  get 'pages/about', to: 'pages#about', as: 'about_page'
  get 'pages/how_to_use', to: 'pages#how_to_use', as: 'how_to_use_page'
  get 'pages/educators', to: 'pages#educators', as: 'educators_page'
  get 'pages/feedback', to: 'pages#feedback', as: 'feedback_page'
  devise_for :users
  resources :users, :except => [:index]
  get 'cards/study', to: 'cards#study', as: 'study_page'
  resources :cards
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<ul>
<li><%= link_to('Home', home_page_path)%></li>
<li><%= link_to('About', about_page_path)%></li>
<li><%= link_to('How to use app', how_to_use_page_path)%></li>
<li><%= link_to('For Educators', educators_page_path)%></li>
</ul>

app/views/layouts/_sidebar.html.erb
<aside id='user-details'>
    <% if user_signed_in? %>
        <%= image_tag(current_user.profile_picture, height: '50', width: '50') if current_user.profile_picture.attached? %>
        <h2><%= current_user.name %></h2>
        <h3>My Classes:</h3>
        <ul>
        <% if @courses %>
            <% if current_user.has_role?(:educator) %>
                <% # list owned classes%>
                <% if @educators_courses %>
                    Your exact courses
                    <% @educators_courses.each do |course| %>
                        <li><% course.name %></li>
                    <% end %>
                <% end %>
                <% @courses.each do |course| %>
                    <li><%= course.name %>
                    <%= link_to('View', course_path(course))%></li>
                    <br>
                <% end %>
            <% else %>
                <% # list enrolled courses with buttons to remove enrollment %>
            <% end %>
        <% end %>
        </ul>
        <ul>
            <li><%= link_to('Edit profile', edit_user_path(current_user))%>
            <li><%= link_to('Logout', destroy_user_session_path) %></li>
        </ul>
    <% end %>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlashcardApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="alert"><%= alert %></p>
    
    <ul>
      <% if user_signed_in? %>
        
      <% else %>
        <li><%= link_to('Login', new_user_session_path) %></li>
        <li><%= link_to('Sign Up', new_user_registration_path) %></li>
      <% end %>
    </ul>
    <div id='main'>
      <%= render 'layouts/sidebar' %>
      <section id='content'>
        <p class="notice"><%= notice %></p>
        <%= yield %>
      </section>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>